# Generated by Django 3.2.5 on 2021-07-16 23:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField()),
                ('num_players', models.IntegerField()),
                ('losers', models.ManyToManyField(blank=True, related_name='lose', to=settings.AUTH_USER_MODEL)),
                ('winners', models.ManyToManyField(blank=True, related_name='win', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
