# Generated by Django 3.2.5 on 2021-07-21 00:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_auto_20210721_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='losers',
            field=models.ManyToManyField(blank=True, related_name='lose', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='played_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='win', to=settings.AUTH_USER_MODEL),
        ),
    ]
