# Generated by Django 3.2.5 on 2021-07-21 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210721_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='losers',
            field=models.ManyToManyField(blank=True, related_name='lose', to='dashboard.Score'),
        ),
        migrations.AlterField(
            model_name='game',
            name='played_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='game',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='win', to='dashboard.Score'),
        ),
    ]
