# Generated by Django 3.2.5 on 2021-07-21 05:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210721_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='losers',
        ),
        migrations.RemoveField(
            model_name='game',
            name='winners',
        ),
        migrations.AddField(
            model_name='score',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='win',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
