# Generated by Django 3.2.5 on 2021-07-21 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210721_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='win',
        ),
    ]
