# Generated by Django 3.2.5 on 2021-07-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_score_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='win',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
