# Generated by Django 3.2.5 on 2021-07-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_score_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
