# Generated by Django 3.2.5 on 2021-07-21 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_score_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='played_at',
            field=models.DateField(default=datetime.date(2021, 7, 21)),
        ),
    ]
