# Generated by Django 3.2.5 on 2021-07-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_game_played_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='played_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
