# Generated by Django 3.2.5 on 2021-07-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_game_played_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='win',
            field=models.NullBooleanField(default=False),
        ),
    ]
