# Generated by Django 3.2.5 on 2021-07-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_score_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='win',
            field=models.NullBooleanField(),
        ),
    ]
