# Generated by Django 3.2.5 on 2021-07-21 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_score_win'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='win',
        ),
    ]
