# Generated by Django 3.2.5 on 2021-07-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_score_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='played_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
