# Generated by Django 3.2.5 on 2021-07-21 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_game_played_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='score',
        ),
    ]
