# Generated by Django 3.2.5 on 2021-07-21 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_score_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='played_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
