# Generated by Django 3.2.5 on 2021-07-21 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0019_auto_20210721_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='played_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
