# Generated by Django 3.2.5 on 2021-07-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20210721_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='win',
            field=models.NullBooleanField(),
        ),
    ]
