# Generated by Django 3.2.5 on 2021-07-21 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_score_win'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['win', 'player']},
        ),
    ]
